### ISSUE TITLE
Automatic loading of PDB information

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#11]
If we follow the workflow idiom described in the previous issue, it should be possible to support automatic loading of symbols from PDB, since the session will be "locked" to a particular executable.

**Comment by dimitry-** [comment]
We had some discussions about this and the bottom line is that since symbol loading could take significant time especially when they are loaded from a remote - we want user to trigger this explicitly. Note that sampling usually involves multiple shared libraries so we probably will end up loading a symbols for multiple modules.

**Comment by dimitry-** [comment]
Tracked internally in http://b/159103838

**Comment by florian-kuebler** [comment]
This has been done recently.
