### ISSUE TITLE
how to install on windows?

### ISSUE THREAD

**Issue by sagunkho** [google/orbit#1961]
Hi, I couldn't find this (or maybe I hadn't searched properly) but how do I install this on windows / macOS?

**Comment by florian-kuebler** [comment]
Hi, thanks for reaching out. 
Unfortunately, macOS is currently not supported. 

For Windows local profiling, you can use the [1.0.2 release](https://github.com/google/orbit/releases/tag/v1.0.2). We dropped Windows support in our recent versions due to major refactorings and a shift to Linux, but have it in our backlog to reactivate at some point.
