### ISSUE TITLE
Bootsrtap script on Windows 10 fails when try to find path to "py"

### ISSUE THREAD

**Issue by zloywolk** [google/orbit#4661]
Hello, trying to build nightli release using `bootstrap_orbit.ps1` fails on Windows system where Python installed from Microsoft Store.
There is script try to find py, which not provided by Python Installer

```powershell
# file: "third_party/conan/configs/install.ps1"
# Here is error
$py = Get-Command py -ErrorAction Stop

# Installs conan config (build settings, public remotes, conan profiles, conan options). Have a look in \third_party\conan\configs\windows for more information.
$process = Start-Process $py.Path -Wait -NoNewWindow -ErrorAction Stop -PassThru -ArgumentList "-3", "-m","conans.conan","config","install","$PSScriptRoot\windows"
if ($process.ExitCode -ne 0) { Throw "Error while installing conan config." }
```

![image](https://user-images.githubusercontent.com/5486665/209642132-13a25af9-2cf1-4d13-a238-db5d3ff49e55.png)

I changed this line on ```python```, then remove argument `"-3"` from `Start-Process` in the all ps1 files and build succesfull.

**My environment**

- System: Windows 10 Pro 22H2
- Python: 3.9.13  from Microsoft Store
- Qt Libs: 5.15.17 (from source)
- CMake 3.25
- Compiler VS 2022 (17.4.3)

**Comment by beckerhe** [comment]
Hey Andrey,
that's not unexpected. We strictly require the `py` Python Launcher to be available in the PATH. Otherwise calling the correct version of Python on Windows would be hard. The launcher is our best bet to launch the correct version of Python3. It's unfortunate that it's not available when Python is installed from the Microsoft Store. Or maybe it's just not available in the PATH?

The latter is the more likely option. I currently don't have a machine available where I can test this.

Anyway, I see the following options for you:

1. Install an official distribution of Python (from python.org, not from the Microsoft Store)
2. Figure out if `py.exe` is installed somewhere and just not made available in the PATH.
3. Change the scripts to your convenience (as you have done already).

**Comment by zloywolk** [comment]
@beckerhe , thanks for your reply.
I successfuly built Orbit with python from Microsoft Store (patched installer ps files and one *.cpp (HttpDownloadManagerTest.cpp) with my python3.exe). For me thats enough.
It is not bug but notification that python3 Microsoft Store not supported.

Happy New Year!
