### ISSUE TITLE
Can't compile Windows - openssl/1.1.1s

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4663]
```
*** Installing runtime programs
Copying: apps//openssl.exe to C:/Users/Pierric/.conan/data/openssl/1.1.1s/_/_/package/5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b//bin/openssl.exe
Can't Open apps//openssl.pdb at .\util\copy.pl line 68.
NMAKE : fatal error U1077: 'C:\Users\Pierric\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe' : return code '0x2'
Stop.
```

**Comment by pierricgimmig** [comment]
This is running `.\bootstrap-orbit.ps1 msvc2019_relwithdebinfo`, on Windows 10

**Comment by beckerhe** [comment]
I've seen this problem before and wasn't able to fully track it down. My suspicion is that while openssl is trying to copy the file a virus scanner or the Windows Search Indexer still have an exclusive lock on the file, so opening the file failed.

Compiling on a machine without a virus scanner installed and the search indexer disabled always 100% worked for me. But I can't say for sure if the problem wasn't just solved by compiling on a different machine. I wasn't able to disable the Virus Scanner on the failing machine due to company policies.

**Comment by pierricgimmig** [comment]
Thanks for the info @beckerhe, I don't have more info, but will update this thread when I do.

**Comment by florian-kuebler** [comment]
Is there any update on this?

**Comment by pierricgimmig** [comment]
This is fixed, but we have other build issues, see https://github.com/google/orbit/issues/4844
